name: Package source code and upload artifact
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm i

    - name: package source
      run: zip -r secret-clickers.zip src/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: secret-clickers-package
        path: secret-clickers.zip